import json
from .grammar_examples import build_example_sets, corpus_for_seed


def lesson(level, zh, en, pattern, explanation, *examples):
    return (level, zh, en, pattern, explanation, list(examples))


# Original teaching copy aligned to the GF 0025-2021 beginner grammar outline.
# HSK 1 contains the 48 Band 1 points. HSK 2 contains 35 added/reinforced
# structures, for 83 cumulative beginner lessons. HSK 3 remains a starter set.
GRAMMAR_POINTS = [
    lesson(1, "是字句", "Identifying with 是", "A 是 B",
           "Use 是 to identify or classify someone or something. A simple adjective does not need 是.",
           ("我是学生。", "I am a student."), ("这是我姐姐。", "This is my older sister.")),
    lesson(1, "有字句", "Having and existence with 有", "A 有 B / Place 有 B",
           "有 can mean “to have” or introduce something that exists in a place.",
           ("我有一个哥哥。", "I have an older brother."), ("桌上有一本书。", "There is a book on the table.")),
    lesson(1, "吗问句", "Yes–no questions with 吗", "Statement + 吗？",
           "Add 吗 to a statement to ask a neutral yes–no question without changing the word order.",
           ("你是老师吗？", "Are you a teacher?"), ("她今天来吗？", "Is she coming today?")),
    lesson(1, "不和没", "Negation with 不 and 没", "不 + habit/future · 没 + past event/有",
           "Use 不 for habits, facts, and choices; use 没 for events that did not happen and with 有.",
           ("我不喝咖啡。", "I do not drink coffee."), ("他昨天没来。", "He did not come yesterday.")),
    lesson(1, "的字短语", "Possession and description with 的", "Owner/description + 的 + noun",
           "的 links an owner or description to a noun. It is often omitted before close family terms.",
           ("这是我的书。", "This is my book."), ("她是我妈妈。", "She is my mother.")),
    lesson(1, "在和位置", "Location with 在", "Subject + 在 + place",
           "Put 在 before a place to say where someone or something is or where an action happens.",
           ("妈妈在家。", "Mom is at home."), ("我在学校学习。", "I study at school.")),
    lesson(1, "想和要", "Wanting with 想 and 要", "Subject + 想/要 + verb or noun",
           "想 expresses a softer wish or plan. 要 is stronger and can also express a need.",
           ("我想吃米饭。", "I want to eat rice."), ("我要一杯茶。", "I would like a cup of tea.")),
    lesson(1, "基本方位词", "Basic position words", "noun + 上/下/里/外/前/后",
           "Position words locate something relative to a place or object.",
           ("猫在桌子下。", "The cat is under the table."), ("学校前面有商店。", "There is a shop in front of the school.")),
    lesson(1, "会和能", "Ability with 会 and 能", "Subject + 会/能 + verb",
           "会 describes a learned skill; 能 describes whether circumstances or ability make an action possible.",
           ("我会说中文。", "I can speak Chinese."), ("你今天能来吗？", "Can you come today?")),
    lesson(1, "疑问代词", "Question words", "谁/什么/哪/哪儿/几/多少/怎么",
           "Put the question word where the missing information would normally appear; do not move it to the front.",
           ("你找谁？", "Who are you looking for?"), ("你想吃什么？", "What do you want to eat?")),
    lesson(1, "人称代词", "Personal pronouns", "我/你/他/她/我们/你们/他们",
           "Personal pronouns stand in for people. Add 们 to form the usual human plural.",
           ("我们都是学生。", "We are all students."), ("他们住在北京。", "They live in Beijing.")),
    lesson(1, "指示代词", "Demonstratives", "这/那 + measure word + noun",
           "这 points to something near the speaker and 那 to something farther away.",
           ("这个人是我朋友。", "This person is my friend."), ("那本书很好。", "That book is good.")),
    lesson(1, "基本数字", "Cardinal numbers", "零、一、二、三…十、百",
           "Numbers come before a measure word and noun. Use 两 rather than 二 before many measure words.",
           ("我有两本书。", "I have two books."), ("今天来了十个人。", "Ten people came today.")),
    lesson(1, "基本量词", "Core measure words", "number/demonstrative + 个/本/杯/张 + noun",
           "A measure word normally sits between a number or demonstrative and its noun.",
           ("我买了三本书。", "I bought three books."), ("请给我一杯水。", "Please give me a glass of water.")),
    lesson(1, "数量短语", "Number–measure phrases", "number + measure word (+ noun)",
           "A number and measure word form one unit that can count a noun or stand alone when the noun is clear.",
           ("桌上有五个苹果。", "There are five apples on the table."), ("我要两个。", "I want two.")),
    lesson(1, "程度副词", "Degree adverbs", "很/非常/太/真/最 + adjective",
           "Degree adverbs describe how strong a quality is. 很 often links a subject to an adjective without strong emphasis.",
           ("今天天气很好。", "The weather is nice today."), ("这个菜太辣了。", "This dish is too spicy.")),
    lesson(1, "都和一起", "Scope with 都 and 一起", "plural subject + 都 / subject + 一起 + verb",
           "都 means “all” and normally follows the group it covers. 一起 marks a shared action.",
           ("我们都是学生。", "We are all students."), ("我们一起吃饭吧。", "Let’s eat together.")),
    lesson(1, "时间副词", "Time and immediacy adverbs", "马上/先/有时 + verb",
           "Time adverbs usually appear after the subject and before the main verb.",
           ("我马上回来。", "I will come back right away."), ("她有时坐地铁。", "She sometimes takes the metro.")),
    lesson(1, "常常和再", "Frequency and repetition", "常常 + verb · 再 + verb",
           "常常 describes a repeated habit. 再 asks for or predicts another occurrence.",
           ("我常常去图书馆。", "I often go to the library."), ("请再说一次。", "Please say it one more time.")),
    lesson(1, "还和也", "Also and still", "subject + 也/还 + predicate",
           "也 adds a parallel fact; 还 can mean “also,” “still,” or “in addition,” depending on context.",
           ("我也喜欢茶。", "I also like tea."), ("他还在学校。", "He is still at school.")),
    lesson(1, "别的命令", "Negative commands with 别", "别 + verb",
           "Place 别 before a verb to tell someone not to do something.",
           ("别说话。", "Do not speak."), ("别忘了带书。", "Do not forget to bring the book.")),
    lesson(1, "从到结构", "From one point to another", "从 A 到 B",
           "从 introduces a starting place or time, and 到 introduces the endpoint.",
           ("我从家走到学校。", "I walk from home to school."), ("商店从九点开到六点。", "The shop is open from nine to six.")),
    lesson(1, "跟和作介词", "With using 跟 and 和", "subject + 跟/和 + person + verb",
           "跟 or 和 before a person can show who joins an action.",
           ("我跟朋友去公园。", "I am going to the park with a friend."), ("她和妈妈住在一起。", "She lives with her mother.")),
    lesson(1, "和跟还是作连词", "Joining choices and nouns", "A 和/跟 B · A 还是 B",
           "和 and 跟 join nouns; 还是 presents alternatives inside a question.",
           ("我买了茶和咖啡。", "I bought tea and coffee."), ("你喝茶还是咖啡？", "Do you drink tea or coffee?")),
    lesson(1, "地字结构", "Adverbial descriptions with 地", "description + 地 + verb",
           "地 turns a description into the manner of an action.",
           ("她高兴地笑了。", "She smiled happily."), ("请慢慢地说。", "Please speak slowly.")),
    lesson(1, "动词后的了", "Completed events with 了", "verb + 了 + object",
           "了 directly after a verb presents an event as completed or bounded.",
           ("我买了一本书。", "I bought a book."), ("他们吃了晚饭。", "They ate dinner.")),
    lesson(1, "句末语气词", "Sentence-final particles", "sentence + 吧/吗/呢",
           "Final particles shape the speaker’s intent: 吧 suggests, 吗 asks, and 呢 keeps a topic or question open.",
           ("我们走吧。", "Let’s go."), ("我的书呢？", "What about my book?")),
    lesson(1, "主语", "The subject", "subject + predicate",
           "The subject is the person or thing being discussed and normally comes before the predicate.",
           ("我学习中文。", "I study Chinese."), ("这本书很好。", "This book is good.")),
    lesson(1, "谓语", "The predicate", "subject + verb/adjective/noun phrase",
           "The predicate says what the subject does, is like, or is identified as.",
           ("妹妹睡觉。", "My younger sister sleeps."), ("今天很冷。", "Today is cold.")),
    lesson(1, "宾语", "The object", "subject + verb + object",
           "The object usually follows the verb and receives or completes its meaning.",
           ("我学习汉语。", "I study Chinese."), ("他买水果。", "He buys fruit.")),
    lesson(1, "定语", "Attributives before nouns", "modifier + 的 + noun",
           "An attributive describes or limits a noun and appears before it, often linked by 的.",
           ("我喜欢新的老师。", "I like the new teacher."), ("这是朋友送的书。", "This is a book a friend gave me.")),
    lesson(1, "状语", "Adverbials before predicates", "subject + time/place/manner + predicate",
           "An adverbial supplies time, place, degree, or manner and normally comes before the verb or adjective.",
           ("我明天去北京。", "I am going to Beijing tomorrow."), ("她在家工作。", "She works at home.")),
    lesson(1, "补语入门", "Introduction to complements", "verb/adjective + complement",
           "A complement follows a verb or adjective and adds information about result, direction, degree, or amount.",
           ("我听懂了。", "I understood what I heard."), ("他走进来了。", "He walked in toward us.")),
    lesson(1, "主谓短语", "Subject–predicate phrases", "subject + predicate",
           "A subject–predicate phrase can describe a complete situation or act as a larger sentence part.",
           ("天气很好。", "The weather is good."), ("他身体健康。", "He is healthy.")),
    lesson(1, "动宾短语", "Verb–object phrases", "verb + object",
           "A verb–object phrase combines an action with the thing it affects.",
           ("我喜欢看书。", "I like reading."), ("我们去吃饭。", "We are going to eat.")),
    lesson(1, "偏正短语", "Modifier–head phrases", "modifier + central word",
           "A modifier narrows or describes the central noun, verb, or adjective that follows it.",
           ("这是中文书。", "This is a Chinese book."), ("他认真学习。", "He studies seriously.")),
    lesson(1, "联合短语", "Coordinated phrases", "A 和/跟 B",
           "Coordinated words or phrases have equal grammatical weight and are often joined with 和 or 跟.",
           ("爸爸和妈妈都在家。", "Dad and Mom are both at home."), ("我学习听和说。", "I practice listening and speaking.")),
    lesson(1, "介词短语", "Prepositional phrases", "在/从/跟 + noun phrase",
           "A preposition and noun phrase together add place, source, companion, or another relation before the predicate.",
           ("我在北京学习。", "I study in Beijing."), ("他从美国来。", "He comes from the United States.")),
    lesson(1, "陈述句", "Statements", "subject + predicate + 。",
           "A statement presents information with normal subject-before-predicate order.",
           ("我家有四个人。", "There are four people in my family."), ("今天是星期五。", "Today is Friday.")),
    lesson(1, "祈使句", "Commands and requests", "请/别 + verb",
           "Commands can use a bare verb; 请 makes a request polite and 别 makes it negative.",
           ("请坐。", "Please sit."), ("别开门。", "Do not open the door.")),
    lesson(1, "感叹句", "Exclamations", "太/真/多么 + adjective + 了！",
           "An exclamation expresses a strong reaction, often with 太…了 or 真.",
           ("今天天气真好！", "The weather is really nice today!"), ("这个孩子太可爱了！", "This child is so cute!")),
    lesson(1, "特指问句", "Wh-questions", "statement position + question word",
           "A question word remains in the same position as the answer it requests.",
           ("你住在哪儿？", "Where do you live?"), ("这是谁的杯子？", "Whose cup is this?")),
    lesson(1, "选择问句", "Alternative questions", "A 还是 B？",
           "Use 还是 between alternatives when asking the listener to choose.",
           ("你坐车还是走路？", "Will you take a vehicle or walk?"), ("今天去还是明天去？", "Are we going today or tomorrow?")),
    lesson(1, "正反问句", "A-not-A questions", "verb/adjective + 不 + verb/adjective？",
           "Repeat the main verb or adjective around 不 to ask for a yes–no choice without 吗.",
           ("你去不去？", "Are you going?"), ("这个菜好不好吃？", "Does this dish taste good?")),
    lesson(1, "状态变化了", "Change of state with sentence-final 了", "new situation + 了",
           "Sentence-final 了 signals that a situation is now different from before.",
           ("天冷了。", "It has become cold."), ("我现在懂了。", "Now I understand.")),
    lesson(1, "进行体", "Ongoing actions", "在/正/正在 + verb (+ 呢)",
           "在, 正, or 正在 before a verb presents an action in progress; 呢 may appear at the end.",
           ("我在写字。", "I am writing."), ("他们正吃饭呢。", "They are eating right now.")),
    lesson(1, "钱数表达", "Talking about prices", "number + 块/元/角/毛/分",
           "Chinese prices place the currency unit after its number; 块 and 毛 are common spoken forms.",
           ("这本书二十块钱。", "This book costs twenty yuan."), ("苹果三块五一斤。", "The apples are 3.5 yuan per jin.")),
    lesson(1, "日期和时间", "Dates and clock time", "year + 年 + month + 月 + day + 日/号",
           "Dates move from larger units to smaller ones; clock time uses 点 and 分 after the hour and minute.",
           ("今天是五月三号。", "Today is May third."), ("我们八点半上课。", "Our class starts at eight thirty.")),

    lesson(2, "了表示完成", "Completed actions with 了", "subject + verb + 了 + object",
           "At Level 2, use 了 with fuller objects and time expressions while distinguishing completion from past time.",
           ("我昨天看了那部电影。", "I watched that movie yesterday."), ("她买了两张火车票。", "She bought two train tickets.")),
    lesson(2, "正在进行", "Actions in progress", "subject + 正在/在 + verb + 呢",
           "正在 or 在 highlights an action underway; 呢 can reinforce the ongoing scene.",
           ("妹妹正在做作业。", "My younger sister is doing homework."), ("他们在开会呢。", "They are having a meeting.")),
    lesson(2, "比字句", "Comparisons with 比", "A 比 B + adjective (+ amount)",
           "Place 比 between two things, then state the quality and optionally the size of the difference.",
           ("哥哥比我高。", "My older brother is taller than me."), ("今天比昨天冷三度。", "Today is three degrees colder than yesterday.")),
    lesson(2, "因为所以", "Cause and result", "因为 cause，所以 result",
           "因为 introduces a reason and 所以 its result. In conversation, one connector can be omitted when the relation is clear.",
           ("因为下雨，所以我没出门。", "Because it rained, I did not go out."), ("我很高兴，因为朋友来了。", "I am happy because my friend came.")),
    lesson(2, "先再然后", "Sequencing actions", "先 A，再/然后 B",
           "Use 先 for the first step and 再 or 然后 for what follows.",
           ("我先吃饭，再做作业。", "I eat first, then do homework."), ("请先买票，然后上车。", "Please buy a ticket first, then board.")),
    lesson(2, "过的经验", "Past experiences with 过", "subject + verb + 过 + object",
           "过 after a verb says an experience has occurred at least once without locating one specific event.",
           ("我去过北京。", "I have been to Beijing."), ("你吃过这个菜吗？", "Have you eaten this dish before?")),
    lesson(2, "方向后缀面边", "Expanded direction words", "上/下/里/外/前/后 + 面/边",
           "面 and 边 form fuller location words; 左边 and 右边 identify the two sides.",
           ("银行在学校对面。", "The bank is across from the school."), ("请坐在我右边。", "Please sit to my right.")),
    lesson(2, "动词重叠", "Reduplicating verbs", "V-V / V一V / ABAB",
           "Reduplication presents a short, light, or tentative action and often softens a request.",
           ("我看看这本书。", "I will take a look at this book."), ("我们讨论讨论这个问题。", "Let’s discuss this issue a little.")),
    lesson(2, "形容词重叠", "Reduplicating adjectives", "AA的 / AABB的",
           "A reduplicated adjective makes a description vivid and usually takes 的 before a noun.",
           ("她有一双大大的眼睛。", "She has a pair of big eyes."), ("房间干干净净的。", "The room is nice and clean.")),
    lesson(2, "可能", "Possibility with 可能", "subject + 可能 + predicate",
           "可能 before the predicate marks an uncertain but plausible situation.",
           ("他可能迟到。", "He might be late."), ("明天可能下雨。", "It may rain tomorrow.")),
    lesson(2, "离合词", "Separable verbs", "verb part + modifier/object + noun part",
           "Some two-character verbs can separate so that quantity, aspect, or another modifier appears between the parts.",
           ("我昨天见了他一面。", "I met him once yesterday."), ("她今天睡了一个午觉。", "She took a nap today.")),
    lesson(2, "自己", "Reflexive 自己", "subject/person + 自己",
           "自己 refers back to the relevant person and can emphasize doing something without help.",
           ("我自己做饭。", "I cook for myself."), ("他相信自己。", "He believes in himself.")),
    lesson(2, "这么那么", "Manner and degree demonstratives", "这么/那么/这样/那样 + adjective/verb",
           "These forms point to a manner, type, or degree: 这- is near/current and 那- is farther or previously mentioned.",
           ("别这么说。", "Do not say it like that."), ("我喜欢这样的生活。", "I like this kind of life.")),
    lesson(2, "万和概数", "Large and approximate numbers", "number + 万 · number + 多",
           "万 groups ten thousand, while 多 after a round number makes an approximate amount above it.",
           ("这个城市有一百多万人。", "This city has more than one million people."), ("那辆车十多万块钱。", "That car costs over one hundred thousand yuan.")),
    lesson(2, "扩展量词", "Expanded measure words", "number + 条/位/间/名/包/次 + noun",
           "Select a measure word that matches the noun or event being counted.",
           ("她买了两条鱼。", "She bought two fish."), ("我去过三次上海。", "I have been to Shanghai three times.")),
    lesson(2, "已经", "Already with 已经", "subject + 已经 + predicate + 了",
           "已经 marks that something has happened or reached a state earlier than the reference point; 了 often closes the sentence.",
           ("我已经吃饭了。", "I have already eaten."), ("电影已经开始了。", "The movie has already started.")),
    lesson(2, "着表示持续", "Continuous state with 着", "verb + 着 (+ object)",
           "着 after a verb presents a continuing state, often the state left by an action.",
           ("门开着。", "The door is open."), ("墙上挂着一张照片。", "A photo is hanging on the wall.")),
    lesson(2, "就", "Early sequence and result with 就", "condition/time + 就 + result",
           "就 can mark that something happens promptly, earlier than expected, or as the direct result of a condition.",
           ("我六点就起床了。", "I got up as early as six."), ("你到了就给我打电话。", "Call me as soon as you arrive.")),
    lesson(2, "多问程度", "Asking degree with 多", "多 + adjective？",
           "多 before an adjective asks for a measurable degree such as age, distance, height, or duration.",
           ("你妹妹多大？", "How old is your younger sister?"), ("这座楼多高？", "How tall is this building?")),
    lesson(2, "一点儿和有点儿", "A little: 一点儿 vs 有点儿", "adjective + 一点儿 · 有点儿 + adjective",
           "一点儿 after an adjective requests a small change; 有点儿 before it often presents a mildly unwanted quality.",
           ("请说慢一点儿。", "Please speak a little more slowly."), ("今天有点儿冷。", "It is a little cold today.")),
    lesson(2, "是的强调句", "Emphasis with 是…的", "是 + focused detail + verb + 的",
           "Use 是…的 to highlight a detail of a known completed event, such as time, place, or manner.",
           ("我是昨天来的。", "It was yesterday that I came."), ("她是坐地铁去的。", "She went by metro.")),
    lesson(2, "从和离", "Starting point and distance", "从 + origin · place A + 离 + place B",
           "从 introduces where an action starts; 离 describes the distance between two places or times.",
           ("我从公司回家。", "I return home from the office."), ("我家离学校很近。", "My home is close to the school.")),
    lesson(2, "但和但是", "Contrast with 但 and 但是", "statement 1，但/但是 statement 2",
           "但 and 但是 introduce information that contrasts with what came before.",
           ("这件衣服很好看，但是太贵了。", "This clothing looks nice, but it is too expensive."), ("我想去，但今天没时间。", "I want to go, but I have no time today.")),
    lesson(2, "转折复句", "Although… but…", "虽然 A，但是 B",
           "虽然 acknowledges one fact, while 但是 presents a result that runs against the expectation it creates.",
           ("虽然下雨，但是我们还是去了。", "Although it rained, we still went."), ("虽然很累，但是她很开心。", "Although she is tired, she is happy.")),
    lesson(2, "让字兼语句", "Causing or allowing with 让", "A + 让 + B + verb",
           "让 introduces the person who is caused or allowed to perform the following action.",
           ("老师让我们读课文。", "The teacher had us read the text."), ("妈妈不让我出去。", "Mom will not let me go out.")),
    lesson(2, "连动句", "Serial verb sentences", "subject + verb phrase 1 + verb phrase 2",
           "Two verb phrases can share one subject when they describe a sequence, purpose, or manner.",
           ("我坐地铁去上班。", "I take the metro to work."), ("她去商店买水果。", "She goes to the shop to buy fruit.")),
    lesson(2, "的字短语作名词", "Phrase + 的: modifying or replacing a noun", "phrase + 的 + noun / phrase + 的",
           "A complete phrase can modify a following noun; when that noun is already clear, the phrase ending in 的 can stand alone.",
           ("我喜欢你做的饭。", "I like the food that you made."), ("红的是我的。", "The red one is mine.")),
    lesson(2, "什么的", "Open-ended examples with 什么的", "examples + 什么的",
           "什么的 follows examples to mean “and things like that,” leaving the list open.",
           ("我喜欢看电影、听音乐什么的。", "I like watching movies, listening to music, and things like that."), ("水果、面包什么的都买好了。", "Fruit, bread, and the like have all been bought.")),
    lesson(2, "即将发生", "Something about to happen", "要/快要/就要 + verb + 了",
           "These patterns present an event as imminent; a time phrase can make the timing more precise.",
           ("火车快要到了。", "The train is about to arrive."), ("我们下周就要考试了。", "We are going to have an exam next week.")),
    lesson(2, "都已经了", "All this time with 都…了", "都 + duration/time + 了",
           "都…了 emphasizes that a point in time or amount has already been reached, often with surprise or impatience.",
           ("都十二点了，你还不睡？", "It is already twelve; why are you still awake?"), ("孩子都十岁了。", "The child is already ten.")),
    lesson(2, "还是吧", "A softened recommendation", "还是 + verb phrase + 吧",
           "还是…吧 recommends one option after considering the situation, similar to “better to…”",
           ("外面下雨，我们还是坐车吧。", "It is raining; we had better take a vehicle."), ("你累了，还是休息吧。", "You are tired; you should rest.")),
    lesson(2, "结果补语", "Result complements", "verb + 完/好/到/懂/见/错",
           "A result complement states the outcome reached by an action.",
           ("我看完这本书了。", "I finished reading this book."), ("你听懂了吗？", "Did you understand what you heard?")),
    lesson(2, "趋向补语", "Directional complements", "verb + 来/去 · verb + 上/下/进/出/回 + 来/去",
           "A directional complement traces movement and shows whether it comes toward or goes away from the speaker’s viewpoint.",
           ("请进来坐。", "Please come in and sit."), ("他跑出去了。", "He ran out away from here.")),
    lesson(2, "程度补语", "Degree complements with 得", "verb + 得 + description",
           "得 links an action to a description of how well, quickly, or otherwise it is performed.",
           ("她中文说得很好。", "She speaks Chinese very well."), ("弟弟跑得很快。", "My younger brother runs very fast.")),
    lesson(2, "时量补语", "Duration complements", "verb + duration / verb + object + verb + duration",
           "A duration complement follows the verb to say how long an action or state lasts.",
           ("我学了两年中文。", "I studied Chinese for two years."), ("她在北京住了三个月。", "She lived in Beijing for three months.")),
    lesson(2, "一样和没有", "More comparison patterns", "A 跟 B 一样 · A 没有 B + adjective",
           "一样 marks equality; 没有 in a comparison says A does not reach B’s degree.",
           ("我跟姐姐一样高。", "I am as tall as my older sister."), ("今天没有昨天热。", "Today is not as hot as yesterday.")),

    lesson(3, "把字句", "Disposal sentences with 把", "subject + 把 + object + verb/result",
           "把 moves a specific object forward when the action changes, moves, or disposes of it.",
           ("请把门打开。", "Please open the door."), ("我把书放在桌上了。", "I put the book on the table.")),
    lesson(3, "被字句", "Passive sentences with 被", "receiver + 被 + actor + verb",
           "被 marks the receiver of an action and can introduce the actor.",
           ("杯子被弟弟打坏了。", "The cup was broken by my younger brother."), ("他被老师表扬了。", "He was praised by the teacher.")),
    lesson(3, "虽然但是", "Contrast with 虽然…但是…", "虽然 condition，但是 contrast",
           "This Level 3 lesson extends contrast to longer clauses and implied expectations.",
           ("虽然很忙，但是她每天都运动。", "Although she is busy, she exercises every day."), ("虽然没见过面，但是我们常聊天。", "Although we have not met, we often chat.")),
    lesson(3, "越来越", "Increasing change", "越来越 + adjective/mental verb",
           "越来越 describes a quality that keeps increasing over time.",
           ("天气越来越冷了。", "The weather is getting colder."), ("我的中文越来越好了。", "My Chinese is getting better.")),
    lesson(3, "一边一边", "Simultaneous actions", "一边 A，一边 B",
           "一边…一边… presents two actions performed at the same time.",
           ("我一边听音乐，一边做作业。", "I listen to music while doing homework."), ("她一边走路，一边打电话。", "She talks on the phone while walking.")),
    lesson(3, "除了以外", "Besides and except", "除了 A 以外，还/都 B",
           "除了…以外 can add an item with 还 or exclude one from a group with 都.",
           ("除了中文以外，我还学习英语。", "Besides Chinese, I also study English."), ("除了他以外，大家都来了。", "Everyone came except him.")),
]


def seed_grammar(conn) -> None:
    """Insert new lessons and refresh teaching copy without changing existing IDs."""
    corpus = corpus_for_seed(conn)
    level_numbers: dict[int, int] = {}
    curriculum_order: dict[str, tuple[int, int]] = {}
    for level, zh, *_rest in GRAMMAR_POINTS:
        level_numbers[level] = level_numbers.get(level, 0) + 1
        curriculum_order[zh] = (level, level_numbers[level])
    level_numbers.clear()
    for level, zh, en, pattern, explanation, examples in GRAMMAR_POINTS:
        level_numbers[level] = level_numbers.get(level, 0) + 1
        base_examples = [{"zh": example_zh, "en": example_en}
                         for example_zh, example_en in examples]
        point = {
            "level": level, "title_zh": zh, "title_en": en,
            "pattern": pattern, "explanation": explanation,
            "lesson_number": level_numbers[level],
            "curriculum_order": curriculum_order,
        }
        theory_examples, practice_examples = build_example_sets(
            conn, point, base_examples, corpus
        )
        payload = json.dumps(base_examples, ensure_ascii=False)
        theory_payload = json.dumps(theory_examples, ensure_ascii=False)
        practice_payload = json.dumps(practice_examples, ensure_ascii=False)
        existing = conn.execute(
            "SELECT id FROM grammar_point WHERE level=? AND title_zh=? ORDER BY id LIMIT 1",
            (level, zh),
        ).fetchone()
        if existing:
            conn.execute(
                "UPDATE grammar_point SET title_en=?,pattern=?,explanation=?,examples_json=?,"
                "theory_examples_json=?,practice_examples_json=? "
                "WHERE id=?",
                (en, pattern, explanation, payload, theory_payload, practice_payload,
                 existing["id"]),
            )
        else:
            conn.execute(
                "INSERT INTO grammar_point(level,title_zh,title_en,pattern,explanation,"
                "examples_json,theory_examples_json,practice_examples_json) "
                "VALUES(?,?,?,?,?,?,?,?)",
                (level, zh, en, pattern, explanation, payload, theory_payload,
                 practice_payload),
            )
    conn.commit()
